version: '3.8'

services:
  neural-trading:
    build: 
      context: .
      dockerfile: Dockerfile.neural
    container_name: neural-trading-api
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/neural/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - neural-net
    depends_on:
      - redis

  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: neural-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./.env:/app/.env
    depends_on:
      - neural-trading
    restart: unless-stopped
    networks:
      - neural-net

  redis:
    image: redis:7-alpine
    container_name: neural-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - neural-net

networks:
  neural-net:
    driver: bridge

volumes:
  redis_data: