services:
  neural-trading:
    build: .
    container_name: neural-trading-api
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - neural-net

  dashboard:
    build: .
    container_name: neural-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    command: ["streamlit", "run", "neural_monitor_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - neural-trading
    restart: unless-stopped
    networks:
      - neural-net

  redis:
    image: redis:7-alpine
    container_name: neural-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - neural-net

networks:
  neural-net:
    driver: bridge
